version: '3'
services:
  app:
    container_name: app
    network_mode: bridge
    image: app
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - ovsmdb
    links:
      - ovsmdb
  ovsmdb:
    image: postgres
    network_mode: bridge
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=lore
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ovsmdb